#!/usr/bin/env bash
# TheBigOne
 
 if [ $@ != 3 ]; then
 	echo "Usage: manage_my_process {start|stop|restart}"
 fi

 case "$1" in
 	"start" ) 
	bash ./manage_my_process
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"
 	;;

 	"stop" )
		kill "$(pidof manage_my_process)"
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
 	;;
	"restart" )
		kill "$(pidof my_process.pid)"
		rm /var/run/my_process.pid
		./manage_my_process
		
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;

 esac
