#!/usr/bin/env bash
# User => Id => Dict
#user="root:x:0:0:root:/root:/bin/bash"
#f_id=${line#*:*:}
#user_id=${f_id%%:*}
#user_name=${line%%:*}
#user_dict="/${line##*:/}"
echo "User Name : $user_name"
echo "User id : $user_id"
echo "User dict : $user_dict"

while IFS= read -r line
do
	f_id=${line#*:*:}
	user_id=${f_id%%:*}
	user_name=${line%%:*}
	user_dict="/${line##*:/}"
	echo "$user_name:$user_id:$user_dict"
done < "/etc/passwd"
