#!/usr/bin/env bash
# File info
file="school"
if [[ ! -f $file ]]; then
	echo "school file does not exist"

elif [[ -n $file ]]; then
	echo "school file exists"
	if [[ ! -s $file ]]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [[ -f $file ]]; then
		echo "school is a regular file"
	fi
fi
